# Generated by Django 4.0.5 on 2022-06-03 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account_user',
            fields=[
                ('id', models.AutoField(db_column='account_no', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('card_no', models.CharField(max_length=16)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
            managers=[
                ('user_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('receiver_no', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('notes', models.CharField(max_length=100)),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=6)),
                ('card_no', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
