# Generated by Django 4.0.5 on 2022-06-04 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Websitebank', '0002_payments_delete_account_user_delete_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='profiles',
        ),
    ]
