# Generated by Django 4.0.5 on 2022-06-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Websitebank', '0003_rename_profile_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Websitebank.profiles')),
            ],
        ),
    ]
