# Generated by Django 4.0.5 on 2022-06-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Websitebank', '0005_photos_profilepic_delete_profileimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
        migrations.DeleteModel(
            name='profilepic',
        ),
    ]
